name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/install-action@nextest
      - uses: actions/checkout@v3
      - run: cargo nextest run

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy
